# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2017-05-04 11:32
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='userdata',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('blog_title', models.CharField(max_length=200)),
                ('blog_description', models.CharField(max_length=2000)),
            ],
        ),
    ]
